# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [7]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/python/ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/python/ana\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/python/ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/python/ana\\Library\\includ

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [11]:
v0 = np.array([[1, 0, 0, 2],
             [0, 0, 1, 1],
             [9, 9, 9, 0]])
print("%d bytes" % (v0.size * v0.itemsize))

48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
#python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
v1 = np.zeros(10)
v1[4] = 1
print(v1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
v2 = np.arange(10,50, dtype=float)
print(v2)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
v2 = v2[::-1]
print(v2)

[49. 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32.
 31. 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14.
 13. 12. 11. 10.]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
M = np.arange(9, dtype=float).reshape(3, 3)
print(M)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
print(np.nonzero([1, 2, 0, 0, 4, 0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
print(np.random.random((3, 3, 3)))

[[[0.37260625 0.2792126  0.73206746]
  [0.32485826 0.46704383 0.6270689 ]
  [0.80276572 0.78140104 0.00682487]]

 [[0.55278419 0.47094802 0.43971556]
  [0.35162784 0.39104909 0.17311746]
  [0.68916875 0.31406598 0.6570877 ]]

 [[0.78118817 0.88070842 0.99819045]
  [0.52312446 0.17470763 0.43232436]
  [0.23280438 0.26940003 0.81094093]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
M = np.random.random((10, 10))
print(M)
print(M.min(), M.max())

[[0.44938533 0.15928194 0.35078403 0.52914611 0.35435205 0.93347784
  0.80009753 0.98421208 0.53136132 0.94670136]
 [0.54743101 0.54931374 0.66984519 0.15285095 0.86038638 0.41537566
  0.83794166 0.39593228 0.29387541 0.49419449]
 [0.8236368  0.62550816 0.22288045 0.22155938 0.29732489 0.80484737
  0.59398975 0.85078389 0.1395576  0.64895224]
 [0.07730964 0.05223655 0.67525003 0.0484614  0.87294156 0.64154245
  0.58485594 0.71174427 0.82804768 0.43098847]
 [0.4419296  0.1567613  0.10555253 0.67262185 0.59704282 0.53591695
  0.20227116 0.9428119  0.60698856 0.59817966]
 [0.39258464 0.22857808 0.26725595 0.47064306 0.74796783 0.13603125
  0.92528412 0.54303631 0.41130492 0.37796879]
 [0.67948943 0.28765884 0.66373896 0.29990085 0.54555768 0.48038777
  0.49421143 0.22915861 0.34486664 0.03015365]
 [0.11129368 0.92696617 0.12187284 0.99063093 0.56136657 0.17841445
  0.28641427 0.23682382 0.22475953 0.14449875]
 [0.99171918 0.72094025 0.71785883 0.88992828 0.19093008 0.66607212
  0.44356001

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
v3 = np.random.random(30)
print(v3)
print(v3.mean())

[0.52847117 0.28279082 0.85800901 0.09947734 0.05992404 0.82761178
 0.37150825 0.67218207 0.20658222 0.03891872 0.53231667 0.01467699
 0.64956262 0.13896975 0.3162737  0.14737168 0.84232367 0.85031907
 0.55617976 0.36704986 0.02588679 0.51400093 0.32276035 0.80605593
 0.86759637 0.54658075 0.40670565 0.6100192  0.65955614 0.42243508]
0.4514038794187229


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
M1 = np.ones((5, 5))
M1[1:-1, 1:-1] = 0
print(M1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
M2 = np.ones((5, 5))
M2 = np.pad(M2, pad_width=1, mode='constant', constant_values=0)
print(M2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [36]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [40]:
print(np.diag(np.arange(4) + 1, k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
C = np.zeros((8, 8), dtype=int)
C[1::2,::2] = 1
C[::2,1::2] = 1
print(C)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [44]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [46]:
print(np.tile(np.array([[0, 1], [1, 0]]), (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [47]:
M3 = np.random.random((5,5))
M3 = (M3 - np.mean(M3)) / (np.std(M3))
print(M3)

[[ 1.36308253 -0.97895572 -0.8554814   0.6733621   1.32506849]
 [-0.98555896 -0.37724806 -0.80799256 -1.18923625  0.37158054]
 [-0.70284119 -1.46545671  0.94140413  1.86429705 -0.92320683]
 [ 1.19554218 -0.62524616 -1.05057076  1.57131416  0.01836222]
 [-0.12912931  0.11914448  0.79001632  0.93127055 -1.07352085]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
color = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

# Create an array of colors
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color)

# Print the array of colors
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
M1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12],
               [13,14,15]])
M2 = np.array([[1,2],
               [3,4],
               [5,6]])

print(M1 @ M2)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [53]:
M = np.arange(11)

M[(M >= 3) & (M <= 8)] *= -1
print(M)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:
Z = np.zeros(3)
Z**Z
#2 << Z >> 2 illegal :)
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z  illegal :)

array([0., 0., 0.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [60]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\python\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\python\ana\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [68]:
v = np.array([1.1, 2.3, 4.6])
print(np.round(v, 0) )

[1. 2. 5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [69]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([3, 4, 5, 6, 7])

print(np.intersect1d(v1, v2))

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [74]:
with np.errstate(all="ignore"):
    print(np.ones(3) / 0)

[inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [77]:
import datetime 

yesterday = np.datetime64(datetime.datetime.now(), 'D') - np.timedelta64(1, 'D') 
today = np.datetime64(datetime.datetime.now(), 'D') 
tomorrow = np.datetime64(datetime.datetime.now(), 'D') + np.timedelta64(1, 'D') 

print('Yesterday: ', yesterday) 
print('Today: ', today) 
print('Tomorrow: ', tomorrow)

Yesterday:  2023-04-13
Today:  2023-04-14
Tomorrow:  2023-04-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [78]:
print(np.arange('2016-07-01','2016-08-01', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [88]:
v1, v2 = np.arange(5), np.arange(5)
A = v1 @ v2
B = np.eye(5)
print(np.negative(A / 2) * (A + B))

[[-465. -450. -450. -450. -450.]
 [-450. -465. -450. -450. -450.]
 [-450. -450. -465. -450. -450.]
 [-450. -450. -450. -465. -450.]
 [-450. -450. -450. -450. -465.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [91]:
#Method 1:
arr = np.random.randint(0, 10, size=10)
int_arr = np.floor(arr)
print(int_arr) 

#Method 2: 
int_arr = np.trunc(arr)
print(int_arr) 

#Method 3: 
int_arr = np.fix(arr)
print(int_arr) 

#Method 4: 
int_arr = np.around(arr)
print(int_arr)

[4. 7. 9. 8. 3. 1. 4. 6. 2. 9.]
[4. 7. 9. 8. 3. 1. 4. 6. 2. 9.]
[4. 7. 9. 8. 3. 1. 4. 6. 2. 9.]
[4 7 9 8 3 1 4 6 2 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [95]:
M = np.zeros((5,5))
M += np.arange(5)
print(M)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [96]:
def generate_integers():
    for i in range(10):
        yield i

v = np.fromiter(generate_integers(), int)
print(v)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [97]:
v = np.linspace(0,1,11)[1:-1]
print(v)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [101]:
v = np.random.randint(0, 10, size=10)
print(v)
v = np.sort(v)
print(v)

[9 7 7 6 8 6 3 5 3 8]
[3 3 5 6 6 7 7 8 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [104]:
def array_sum(arr):
    summation = 0
    for i in arr:
        summation += i
    return summation

v = [1, 2, 3, 6]
print(array_sum(v))

12


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [105]:
A = np.random.rand(10)
B = np.random.rand(10)

print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [108]:
v = np.zeros(10)
v.flags.writeable = False
v[0] = 0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [109]:
cartesian = np.random.random((10,2))

x = cartesian[:,0]
y = cartesian[:,1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)

polar = np.column_stack((r,theta))
print(polar)

[[0.676329   1.15090057]
 [0.20937617 0.8024577 ]
 [1.01606759 0.34498498]
 [0.39213541 0.01159721]
 [1.08798097 0.75744687]
 [0.91184284 0.234417  ]
 [1.06524877 0.99556422]
 [0.46078115 1.3784542 ]
 [0.87381845 1.19450979]
 [0.79247239 1.42146191]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [111]:
v = np.random.randint(100, size=10)
print(v)
v[v.argmax()] = 0
print(v)

[14 42 91  7 90 46 79 88  3 32]
[14 42  0  7 90 46 79 88  3 32]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [112]:
x_coords = np.arange(0, 1.01, 0.01)
y_coords = np.arange(0, 1.01, 0.01)

coords = np.array(np.meshgrid(x_coords, y_coords)).T.reshape(-1, 2)
print(coords)

[[0.   0.  ]
 [0.   0.01]
 [0.   0.02]
 ...
 [1.   0.98]
 [1.   0.99]
 [1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [114]:
x = np.array([1,2,3])
y = np.array([4,5,6])

C = 1 / np.subtract.outer(x, y)
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [121]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype)
    print('min:', np.iinfo(dtype).min)
    print('max:', np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(dtype)
    print('min:', np.finfo(dtype).min)
    print('max:', np.finfo(dtype).max)
    print('epsilon:', np.finfo(dtype).eps)

<class 'numpy.int8'>
min: -128
max: 127
<class 'numpy.int32'>
min: -2147483648
max: 2147483647
<class 'numpy.int64'>
min: -9223372036854775808
max: 9223372036854775807
<class 'numpy.float32'>
min: -3.4028235e+38
max: 3.4028235e+38
epsilon: 1.1920929e-07
<class 'numpy.float64'>
min: -1.7976931348623157e+308
max: 1.7976931348623157e+308
epsilon: 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [123]:
M = np.eye(10)
print(M)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [125]:
v = np.array([3, 5, 6, 8, 10, 15, 19])
scalar = 12
index = np.argmin(np.absolute(v - scalar))
closest_value = np.take(v, index)
print('Closest value to', scalar, 'is', closest_value)

Closest value to 12 is 10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [132]:
M = np.zeros(6, [ ('position', [('x', float, 1),
                                 ('y', float, 1)]),
                   ('color', [('r', float, 1),
                              ('g', float, 1),
                              ('b', float, 1)])])
print(M)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [137]:
M = np.random.random((100, 2))
x, y = np.atleast_2d(M[:,0], M[:,1])
C = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(C)

[[0.         0.49275668 0.28715557 0.61570494 0.29819819 0.25226884
  0.40826753 0.55219486 0.34309671 0.76206065 0.34613712 0.48058565
  0.27171297 0.36728717 0.60783883 0.71235737 0.52929159 0.49579961
  0.79707468 0.41455028 0.36198328 0.21447675 0.48918497 0.60337152
  0.31866796 0.34695299 0.40255452 0.31882844 0.68540731 0.10146492
  0.2284096  0.33580049 0.74705358 0.62586364 0.37408005 0.48958149
  0.55894738 0.57433709 0.46110235 0.5822471  0.68941891 0.19703683
  0.44685915 0.16870521 0.42231572 0.4622967  0.62757738 0.25604696
  0.23327062 0.79074601 0.29771116 0.6614843  0.07498265 0.38281536
  0.17344269 0.66025857 0.27122377 0.31583243 0.41684225 0.19605062
  0.26027269 0.13430234 0.56761363 0.34472538 0.45428323 0.48422729
  0.69249933 0.32156499 0.20989702 0.43184925 0.3898508  0.72441545
  0.40948868 0.3429863  0.44064429 0.56695252 0.33603314 0.66094597
  0.75420458 0.26816964 0.54498995 0.5882072  0.71050056 0.35984022
  0.74813106 0.52475187 0.44668009 0.56850188 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [145]:
v = np.array([1.2, 2.1, 3.3, 4.32, 5.39])
v0 = v.astype(dtype=np.int32)
print(v, v0)

[1.2  2.1  3.3  4.32 5.39] [1 2 3 4 5]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt
arr = np.genfromtxt('file.csv', delimiter=',')
arr[arr==''] = 0
print(arr)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [146]:
v = np.array([[1, 2, 3], [4, 5, 6]]) 

for index, val in np.ndenumerate(v): 
    print(index, val) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [150]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
v = np.exp(-((d-mu)**2 / (2.0 * sigma**2)))
print(v)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [153]:
p = 7
n = 5
M = np.zeros((n,n))
np.put(M, np.random.choice(range(n*n), p, replace=False), 1)
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [159]:
M = np.random.rand(5, 5)
print(M - M.mean(axis=1, keepdims=True))

[[ 0.13033584  0.31794858 -0.59264049  0.04010499  0.10425108]
 [-0.14614652  0.00233697  0.3364851  -0.24307474  0.05039919]
 [ 0.03871727  0.19977561  0.16529343 -0.29720206 -0.10658424]
 [ 0.55347338 -0.16892926 -0.34592387 -0.09055196  0.05193171]
 [ 0.25347225 -0.33784648 -0.16187588  0.06763241  0.17861769]]


#### 59. How to sort an array by the nth column? (★★☆)

In [161]:
M = np.array([[1, 5, 2], 
              [3, 2, 4], 
              [4, 3, 1]]) 
n = 0
print(M[M[:,n].argsort()])

[[1 5 2]
 [3 2 4]
 [4 3 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [165]:
M = np.array([[1, 2, 3], 
              [4, 5, np.nan], 
              [7, np.nan, 9]]) 
null_columns = np.where(np.isnan(M).any(axis=0))[0]
if len(null_columns) > 0:
    print(f"Array has null columns at indices {null_columns}")
else:
    print("Array does not have null columns")

Array has null columns at indices [1 2]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [166]:
v = np.array([1, 4, 7, 9, 12, 15, 17, 19, 22, 25])
value = 11
nearest_value = np.argmin(np.abs(v - value))
print(v[nearest_value])

12


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [171]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4], [5], [6]])

sum_result = np.zeros((3,3))
for i in range(v1.shape[1]):
    for j in range(v2.shape[0]):
        sum_result[i,j] = v1[0,i] + v2[j,0]
print(sum_result)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [174]:
class myArray():
    def __init__(self, name):
        self.name = name
        self.array = np.array([])
    
    def add_array_elements(self, elements):
        self.array = np.append(self.array, elements)
    
    def remove_array_elements(self, elements):
        self.array = np.delete(self.array, elements)
    
    def get_name(self):
        return self.name
    
    def get_array(self):
        return self.array
    
example = myArray('example_array')
example.add_array_elements([1,2,3])
print(example.get_name())

example_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [181]:
v = np.random.randint(100, size=10)
i = np.random.randint(10, size=10)
print(v, i)
np.add.at(v, i, 1)
print(v)

[79 26 67 27 45 67 85 79 17 87] [4 5 6 6 6 1 3 4 8 5]
[79 27 67 28 47 69 88 79 18 87]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [182]:
X = np.array([1,2,3,4])
I = np.array([0, 1, 2, 2])
F = np.zeros(3)
np.add.at(F, I, X)
print(F)

[1. 2. 7.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [185]:
w, h, c = 256, 256, 256
data = np.random.randint(0, 255, (w, h, c), dtype=np.uint8)
unique_colors = np.unique(data.reshape(-1, c), axis=0)
print(len(unique_colors))

65536


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [187]:
M = np.array([[[[1,2,3],
                [4,5,6]],
               [[7,8,9],
                [10,11,12]]],
              [[[13,14,15],
                [16,17,18]],
               [[19,20,21],
                [22,23,24]]]])
print(np.sum(M, axis=(-2,-1)))

[[ 21  57]
 [ 93 129]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [188]:
D = np.random.randint(100, size=10)
S = np.random.randint(100, size=10)

unique_subsets = np.unique(S)
result = np.array([np.mean(D[S==subset]) for subset in unique_subsets])
print(result)

[96.         26.         28.         18.         59.         45.33333333
 86.          7.        ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [190]:
A = np.array([[3, 5], [2, 4]]) 
B = np.array([[2, 4], [3, 5]]) 
diagonal = np.diagonal(np.dot(A, B) ) 
print(diagonal)

[21 28]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [193]:
M = np.array([1,2,3,4,5])
val = 2
M0 = np.zeros(len(M) + (len(M) - 1) * (val))
M0[:: val + 1] = M
print(M0)

[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [205]:
A = np.ones((5, 5, 3))
B = .3 * np.ones((5, 5))
print(A * B[:, :, None])

[[[0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]]

 [[0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]]

 [[0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]]

 [[0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]]

 [[0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]
  [0.3 0.3 0.3]]]


#### 72. How to swap two rows of an array? (★★★)

In [209]:
M = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])
M[[1,2], :] = M[[2,1], :]
print(M)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [215]:
V =             [[(1,2),(2,3),(3,1)],
                [(4,5),(5,6),(6,4)],
                [(13,14),(14,15),(15,13)],
                [(22,23),(23,24),(24,22)]]
line_segments = np.empty((0,2), dtype = int)
for triplet in V:
    line_segments = np.vstack((line_segments, triplet, triplet[::-1]))
print(line_segments)

[[ 1  2]
 [ 2  3]
 [ 3  1]
 [ 3  1]
 [ 2  3]
 [ 1  2]
 [ 4  5]
 [ 5  6]
 [ 6  4]
 [ 6  4]
 [ 5  6]
 [ 4  5]
 [13 14]
 [14 15]
 [15 13]
 [15 13]
 [14 15]
 [13 14]
 [22 23]
 [23 24]
 [24 22]
 [24 22]
 [23 24]
 [22 23]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [216]:
C = np.array([1, 3, 3, 3])
A = np.repeat(np.arange(len(C)), C)
print(A)
print(np.bincount(A))

[0 1 1 1 2 2 2 3 3 3]
[1 3 3 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [221]:
v = np.array([2., 3., 4., 5., 6., 7., 8., 9.])
sliding_window_size = 3
conv_win = np.ones(sliding_window_size)
conv_win /= 1.0 * sliding_window_size
convolved = np.convolve(v, conv_win, 'valid')
print(convolved)

[3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [222]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.array([[Z[i], Z[i+1], Z[i+2]] for i in range(len(Z) - 2)] + [[Z[-3], Z[-2], Z[-1]]]))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [226]:
M = np.random.uniform(-1.0, 1.0, 20)
print(np.negative(M, out=M))

[-0.34742356  0.86825928 -0.92472562 -0.1445952   0.59598071  0.07758039
  0.22288009  0.57799243 -0.70772716  0.79390792  0.0615906  -0.97969215
 -0.12644159 -0.54797098 -0.0277991  -0.87101158 -0.69459945  0.81797755
 -0.15820615 -0.15166281]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [227]:
P0 = np.array([[1,1],[2,2]])
P1 = np.array([[3,3],[4,4]])
p = np.array([2,3])

distance = np.abs( ((P1[:,1] - P0[:,1]) * p[0] - (P1[:,0] - P0[:,0]) * p[1] + P1[:,0] * P0[:,1] - P1[:,1] * P0[:,0]) /
             np.sqrt( (P1[:,1] - P0[:,1])**2 + (P1[:,0] - P0[:,0])**2 ))

print(distance)

[0.70710678 0.70710678]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [229]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[0.5, 0.5], [1.5, 1.5], [2.5, 2.5]])
line_vectors = P1 - P0
p_vectors = P - P0
cross_products = np.cross(line_vectors, p_vectors)
magnitudes = np.linalg.norm(line_vectors, axis=1)
distances = np.abs(cross_products) / magnitudes
print(distances)

[0.5 0.5 0.5]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [234]:
def extract_subpart(arr, shape, element, fill_value):
    subpart = np.ones(shape, dtype=arr.dtype) * fill_value
    start_x = element[0] - (shape[0] // 2)
    start_y = element[1] - (shape[1] // 2)
    end_x = start_x + shape[0]
    end_y = start_y + shape[1]
    start_x = max(start_x, 0)
    start_y = max(start_y, 0)
    end_x = min(end_x, arr.shape[0])
    end_y = min(end_y, arr.shape[1])
    subpart[start_x:end_x, start_y:end_y] = arr[start_x:end_x, start_y:end_y]    
    return subpart


v = np.array([[1, 2, 3], 
              [5, 6, 7], 
              [9, 10, 11]])

shape = (2, 2)
element = (1, 1)
fill_value = 0

print(extract_subpart(v, shape, element, fill_value))

[[1 2]
 [5 6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [237]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = np.array([Z[i-3:i] for i in range(3, len(Z)+1)])
print(R)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [242]:
M = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(M)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [246]:
M = np.random.randint(0, 20, 20)
print(M)
print(np.bincount(M).argmax())

[ 0 10 18 15  4  3  8 16 19 12 10  0 12  6 15 11  4 11  7 12]
12


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [249]:
from numpy.lib import stride_tricks


Z = np.random.randint(0, 4, (10, 10))
i = 1 + (Z.shape[0] - 3)
j = 1 + (Z.shape[1] - 3)

M = stride_tricks.as_strided(Z, shape=(i, j, 3, 3), strides=Z.strides + Z.strides)
print(M)

[[[[2 2 3]
   [1 1 2]
   [0 3 1]]

  [[2 3 3]
   [1 2 3]
   [3 1 0]]

  [[3 3 2]
   [2 3 0]
   [1 0 2]]

  [[3 2 2]
   [3 0 2]
   [0 2 3]]

  [[2 2 1]
   [0 2 3]
   [2 3 0]]

  [[2 1 1]
   [2 3 2]
   [3 0 2]]

  [[1 1 1]
   [3 2 2]
   [0 2 1]]

  [[1 1 0]
   [2 2 3]
   [2 1 1]]]


 [[[1 1 2]
   [0 3 1]
   [1 2 3]]

  [[1 2 3]
   [3 1 0]
   [2 3 3]]

  [[2 3 0]
   [1 0 2]
   [3 3 1]]

  [[3 0 2]
   [0 2 3]
   [3 1 1]]

  [[0 2 3]
   [2 3 0]
   [1 1 2]]

  [[2 3 2]
   [3 0 2]
   [1 2 3]]

  [[3 2 2]
   [0 2 1]
   [2 3 0]]

  [[2 2 3]
   [2 1 1]
   [3 0 3]]]


 [[[0 3 1]
   [1 2 3]
   [0 0 2]]

  [[3 1 0]
   [2 3 3]
   [0 2 3]]

  [[1 0 2]
   [3 3 1]
   [2 3 3]]

  [[0 2 3]
   [3 1 1]
   [3 3 1]]

  [[2 3 0]
   [1 1 2]
   [3 1 1]]

  [[3 0 2]
   [1 2 3]
   [1 1 3]]

  [[0 2 1]
   [2 3 0]
   [1 3 1]]

  [[2 1 1]
   [3 0 3]
   [3 1 2]]]


 [[[1 2 3]
   [0 0 2]
   [3 0 1]]

  [[2 3 3]
   [0 2 3]
   [0 1 3]]

  [[3 3 1]
   [2 3 3]
   [1 3 2]]

  [[3 1 1]
   [3 3 1]
   [3 2 3]]

  [[1 1 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [264]:
class Sym2DArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

M = Sym2DArray([3, 3])
print(M)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [266]:
p, n = 15, 5
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[75.]
 [75.]
 [75.]
 [75.]
 [75.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [271]:
M = np.ones((16, 16))
val = 9
M0 = np.add.reduceat(np.add.reduceat(M, np.arange(0, M.shape[0], val), axis=0),
                                       np.arange(0, M.shape[1], val), axis=1)
print(M0)

[[81. 63.]
 [63. 49.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [272]:
grid = np.zeros((3,3))
grid[1,1] = 1
print("Initial grid:")
print(grid)
for iteration in range(4):
    new_grid = np.copy(grid)
    for i in range(3):
        for j in range(3):
            live_neighbors = (grid[(i-1)%3, (j-1)%3] + grid[(i-1)%3, j] + 
                              grid[(i-1)%3, (j+1)%3] + grid[i, (j-1)%3] + 
                              grid[i, (j+1)%3] + grid[(i+1)%3, (j-1)%3] +
                              grid[(i+1)%3, j] + grid[(i+1)%3, (j+1)%3])
            if grid[i, j] == 0 and live_neighbors == 3:
                new_grid[i, j] = 1
            elif grid[i, j] == 1 and (live_neighbors < 2 or live_neighbors > 3):
                new_grid[i, j] = 0
            else:
                new_grid[i, j] = grid[i, j]
    grid = np.copy(new_grid)
    print("After iteration {}:".format(iteration+1))
    print(grid)

Initial grid:
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
After iteration 1:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After iteration 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After iteration 3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After iteration 4:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 89. How to get the n largest values of an array (★★★)

In [278]:
v = np.random.randint(250, size=1000)
n = 15
print (v[np.argsort(v)[-n:]])

[244 244 245 245 246 246 246 246 246 246 247 247 247 248 249]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [282]:
def cartesian(v):
    v = [np.asarray(i) for i in v]
    shape = (len(j) for j in v)
    x = np.indices(shape, dtype=int)
    x = x.reshape(len(v), -1).T
    for n, arr in enumerate(v):
        x[:, n] = v[n][x[:, n]]
    return x

print (cartesian(([1, 2], [4, 5, 6], [7, 8])))

[[1 4 7]
 [1 4 8]
 [1 5 7]
 [1 5 8]
 [1 6 7]
 [1 6 8]
 [2 4 7]
 [2 4 8]
 [2 5 7]
 [2 5 8]
 [2 6 7]
 [2 6 8]]


#### 91. How to create a record array from a regular array? (★★★)

In [287]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
rec_arr = np.rec.fromarrays(arr.T, names='a,b,c')

print(rec_arr)

arr = np.array([['John', 23],
                ['Mary', 19],
                ['Bob', 27]])
rec_arr = np.rec.fromarrays(arr.T, names='name,age')

print(rec_arr)

[(1, 2, 3) (4, 5, 6) (7, 8, 9)]
[('John', '23') ('Mary', '19') ('Bob', '27')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [285]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z, 3)
%timeit Z * Z * Z
%timeit np.einsum('i,i,i->i', Z, Z, Z)

1.71 s ± 54.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
381 ms ± 21.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
215 ms ± 20.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [293]:
A = np.random.randint(0, 10, (8,3))
B = np.random.randint(0, 10, (2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
print(np.where(C.any((3,1)).all(1))[0])

[[9 5 2]
 [7 7 3]
 [6 3 3]
 [5 2 7]
 [7 9 2]
 [7 4 7]
 [0 9 7]
 [8 4 0]]
[[9 3]
 [5 2]]
[0 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [298]:
M = np.random.randint(0, 5, (10, 3))
print(M, '\n')

unequal_rows = M[np.any(M != M[0], axis=1)]
print(unequal_rows)

[[2 3 2]
 [1 3 2]
 [3 3 2]
 [0 2 2]
 [2 3 2]
 [0 2 0]
 [1 4 0]
 [1 1 4]
 [2 2 0]
 [0 3 1]] 

[[1 3 2]
 [3 3 2]
 [0 2 2]
 [0 2 0]
 [1 4 0]
 [1 1 4]
 [2 2 0]
 [0 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [301]:
M = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(M[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [310]:
v = np.random.randint(0, 3,(8, 2))
print(v)
u = np.unique(v, axis=0)
print(u)

[[2 1]
 [1 0]
 [0 0]
 [2 0]
 [2 0]
 [1 0]
 [0 2]
 [1 0]]
[[0 0]
 [0 2]
 [1 0]
 [2 0]
 [2 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [314]:
A = np.random.randint(5, size=10)
B = np.random.randint(5, size=10)
print(A, B, sep='\n')

print(np.einsum('i,i', A, B))
print(np.einsum('i,j', A, B))
print(np.einsum('i->', A))
print(np.einsum('i,i', A, B))

[0 4 0 4 2 2 0 1 1 4]
[2 1 4 1 4 4 2 4 2 2]
38
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 8  4 16  4 16 16  8 16  8  8]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 8  4 16  4 16 16  8 16  8  8]
 [ 4  2  8  2  8  8  4  8  4  4]
 [ 4  2  8  2  8  8  4  8  4  4]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 2  1  4  1  4  4  2  4  2  2]
 [ 2  1  4  1  4  4  2  4  2  2]
 [ 8  4 16  4 16 16  8 16  8  8]]
18
38


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [316]:
x = np.random.randint(5, size=10)
y = np.random.randint(5, size=10)
print(x, y, sep='\n')
samples = np.linspace(0, len(x)-1, num=n) 
x_samples = np.interp(samples, np.arange(len(x)), x)
y_samples = np.interp(samples, np.arange(len(y)), y)
samples = np.vstack([x_samples, y_samples]).T
print(samples)

[0 2 3 2 0 0 3 3 2 2]
[2 1 2 4 1 0 1 2 2 1]
[[0.         2.        ]
 [1.28571429 1.35714286]
 [2.28571429 1.28571429]
 [2.92857143 1.92857143]
 [2.42857143 3.14285714]
 [1.57142857 3.35714286]
 [0.28571429 1.42857143]
 [0.         0.5       ]
 [0.42857143 0.14285714]
 [2.35714286 0.78571429]
 [3.         1.42857143]
 [2.92857143 2.        ]
 [2.28571429 2.        ]
 [2.         1.64285714]
 [2.         1.        ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [317]:
X = np.array([[1,2,3],
              [3,3,3],
              [1,1,8],
              [2,3,5],
              [4,3,3]])
n = 6
result = np.array([row for row in X if np.sum(row) == n])
print(result)

[[1 2 3]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [319]:
X = np.arange(11)
# Number of times to resample array
N = 1000
mean_list = []

# Resample the array N times and compute the mean
for n in range(N):
    sample = np.random.choice(X, size=len(X), replace=True)
    mean_list.append(np.mean(sample))

# Compute the 95% confidence interval
CI = np.percentile(mean_list, q=[2.5,97.5])
print("The 95% confidence interval for the mean of the array is:", CI)

The 95% confidence interval for the mean of the array is: [3.18181818 6.72727273]
